var imgs = {
	topSnow: './assets/images/top-snow.png',
	dong: './assets/images/dong.png',
	answers: './assets/images/answer.png',
	answers1: './assets/images/answer1.png',
	answers2: './assets/images/answer2.png',
	answerbig: './assets/images/answerbig.png',
	answerbig1: './assets/images/answerbig1.png',
	answerbig2: './assets/images/answerbig2.png',
	snow: './assets/images/snow.png',
	snow1: './assets/images/snow1.png',
	bg1: './assets/images/bg1.png',
	bg2: './assets/images/bg2.png',
	bg3: './assets/images/bg3.png',
	bg4: './assets/images/bg4.png',
	tigger: './assets/images/tigger.png',
	tiggerSuccess: './assets/images/tigger.png',
	tiggerError: './assets/images/tigger-error.png',
	score: './assets/images/score.png',
	jump: './assets/images/jump.png',
	over: './assets/images/over.png',
	over1: './assets/images/over1.png',
	over2: './assets/images/over2.png',
	over3: './assets/images/over3.png',
	restart: './assets/images/restart.png',
	share: './assets/images/share.png',
	title: './assets/images/title.png',
	start: './assets/images/start.png',
	startbg: './assets/images/startbg.png',
	tree1: './assets/images/tree1.png',
	tree2: './assets/images/tree2.png',
	arrow: './assets/images/arrow.png',
	play: './assets/images/play.png',
	right: './assets/images/right.png',
	error: './assets/images/error.png',
	index: './assets/images/index.jpg',

}
export default imgs;