var imgs = {
	topSnow: './assets/images/top-snow.png',
	dong: './assets/images/dong.png',
	answers: './assets/images/answer.png',
	snow: './assets/images/snow.png',
	tigger: './assets/images/tigger.png',
	tiggerSuccess: './assets/images/tigger.png',
	tiggerError: './assets/images/tigger-error.png',
	score: './assets/images/score.png',
	jump: './assets/images/jump.png',
	over: './assets/images/over.png',
	over1: './assets/images/over1.png',
	over2: './assets/images/over2.png',
	over3: './assets/images/over3.png',
	restart: './assets/images/restart.png',
	share: './assets/images/share.png',
	title: './assets/images/title.png',
	start: './assets/images/start.png',
	index: './assets/images/index.jpg',
}
export default imgs;